id: I157FF080
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:19:45.724275+00:00
last_modified: 2022-12-15 07:19:45.724283+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-006
  eft-text-version: 1.2.6 2021
  title: Toh_147-The_Teaching_on_the_Great_Compassion_of_the_Tathagata-v1
bases:
  8FF7:
    source_metadata: null
    order: 1
    base_file: 8FF7.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
